name: Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore GuidGenerator.sln

      - name: Build solution
        run: dotnet build GuidGenerator.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test GuidGenerator.sln --configuration Release --no-build --verbosity normal

      - name: Create NuGet package
        run: dotnet pack GuidGenerator.Core/GuidGenerator.Core.csproj --configuration Release --output package --no-build

      - name: Upload NuGet package
        uses: actions/upload-artifact@v4
        with:
          name: github-netguidgenerator
          path: package/*.nupkg
          retention-days: 1
 

  # continuous-deployment:
  #   needs: continuous-integration
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: '9.0.x'
